# 16.08. Ein-App-Gefuehl: nav.profile + profilePage + settingsPage in allen
# 22 Dictionary-JSONs (idempotent; Shape-Quelle en.json -> alle gleich).
import json
from pathlib import Path

T = {
 "de": ("Profil","Profilbild","Foto ändern","JPG, PNG oder WebP. Wird automatisch verkleinert und gilt in allen Bereichen.","Persönliche Daten","Anzeigename","Die E-Mail-Adresse kann nicht geändert werden.","Rolle","Administrator","Mitglied","Speichern","Gespeichert.","Speichern fehlgeschlagen.","Erscheinungsbild","Wähle hell, dunkel oder folge deiner Systemeinstellung.","Hell","Dunkel","System","Sprache","Gilt für alle Texte und Oberflächen."),
 "en": ("Profile","Profile photo","Change photo","JPG, PNG or WebP. Resized automatically and used everywhere.","Personal details","Display name","The email address cannot be changed.","Role","Administrator","Member","Save","Saved.","Saving failed.","Appearance","Choose light, dark, or follow your system setting.","Light","Dark","System","Language","Applies to all texts and interfaces."),
 "fr": ("Profil","Photo de profil","Changer la photo","JPG, PNG ou WebP. Redimensionnée automatiquement, utilisée partout.","Données personnelles","Nom affiché","L'adresse e-mail ne peut pas être modifiée.","Rôle","Administrateur","Membre","Enregistrer","Enregistré.","Échec de l'enregistrement.","Apparence","Choisissez clair, sombre ou suivez votre réglage système.","Clair","Sombre","Système","Langue","S'applique à tous les textes et interfaces."),
 "es": ("Perfil","Foto de perfil","Cambiar foto","JPG, PNG o WebP. Se redimensiona automáticamente y se usa en todas partes.","Datos personales","Nombre visible","La dirección de correo no se puede cambiar.","Rol","Administrador","Miembro","Guardar","Guardado.","Error al guardar.","Apariencia","Elige claro, oscuro o sigue tu ajuste del sistema.","Claro","Oscuro","Sistema","Idioma","Se aplica a todos los textos e interfaces."),
 "it": ("Profilo","Foto del profilo","Cambia foto","JPG, PNG o WebP. Ridimensionata automaticamente e usata ovunque.","Dati personali","Nome visualizzato","L'indirizzo e-mail non può essere modificato.","Ruolo","Amministratore","Membro","Salva","Salvato.","Salvataggio non riuscito.","Aspetto","Scegli chiaro, scuro o segui l'impostazione di sistema.","Chiaro","Scuro","Sistema","Lingua","Vale per tutti i testi e le interfacce."),
 "pt": ("Perfil","Foto de perfil","Alterar foto","JPG, PNG ou WebP. Redimensionada automaticamente e usada em todo o lado.","Dados pessoais","Nome apresentado","O endereço de e-mail não pode ser alterado.","Função","Administrador","Membro","Guardar","Guardado.","Falha ao guardar.","Aspeto","Escolha claro, escuro ou siga a definição do sistema.","Claro","Escuro","Sistema","Idioma","Aplica-se a todos os textos e interfaces."),
 "ca": ("Perfil","Foto de perfil","Canvia la foto","JPG, PNG o WebP. Es redimensiona automàticament i s'usa arreu.","Dades personals","Nom visible","L'adreça electrònica no es pot canviar.","Rol","Administrador","Membre","Desa","Desat.","No s'ha pogut desar.","Aparença","Tria clar, fosc o segueix la configuració del sistema.","Clar","Fosc","Sistema","Idioma","S'aplica a tots els textos i interfícies."),
 "nl": ("Profiel","Profielfoto","Foto wijzigen","JPG, PNG of WebP. Wordt automatisch verkleind en overal gebruikt.","Persoonlijke gegevens","Weergavenaam","Het e-mailadres kan niet worden gewijzigd.","Rol","Beheerder","Lid","Opslaan","Opgeslagen.","Opslaan mislukt.","Weergave","Kies licht, donker of volg je systeeminstelling.","Licht","Donker","Systeem","Taal","Geldt voor alle teksten en schermen."),
 "sv": ("Profil","Profilbild","Byt foto","JPG, PNG eller WebP. Förminskas automatiskt och används överallt.","Personuppgifter","Visningsnamn","E-postadressen kan inte ändras.","Roll","Administratör","Medlem","Spara","Sparat.","Det gick inte att spara.","Utseende","Välj ljust, mörkt eller följ systeminställningen.","Ljust","Mörkt","System","Språk","Gäller alla texter och gränssnitt."),
 "da": ("Profil","Profilbillede","Skift foto","JPG, PNG eller WebP. Formindskes automatisk og bruges overalt.","Personlige oplysninger","Visningsnavn","E-mailadressen kan ikke ændres.","Rolle","Administrator","Medlem","Gem","Gemt.","Kunne ikke gemme.","Udseende","Vælg lys, mørk eller følg din systemindstilling.","Lys","Mørk","System","Sprog","Gælder for alle tekster og skærme."),
 "nb": ("Profil","Profilbilde","Bytt bilde","JPG, PNG eller WebP. Forminskes automatisk og brukes overalt.","Personopplysninger","Visningsnavn","E-postadressen kan ikke endres.","Rolle","Administrator","Medlem","Lagre","Lagret.","Kunne ikke lagre.","Utseende","Velg lys, mørk eller følg systeminnstillingen.","Lys","Mørk","System","Språk","Gjelder alle tekster og grensesnitt."),
 "fi": ("Profiili","Profiilikuva","Vaihda kuva","JPG, PNG tai WebP. Pienennetään automaattisesti, käytössä kaikkialla.","Henkilötiedot","Näyttönimi","Sähköpostiosoitetta ei voi muuttaa.","Rooli","Järjestelmänvalvoja","Jäsen","Tallenna","Tallennettu.","Tallennus epäonnistui.","Ulkoasu","Valitse vaalea, tumma tai seuraa järjestelmäasetusta.","Vaalea","Tumma","Järjestelmä","Kieli","Koskee kaikkia tekstejä ja näkymiä."),
 "et": ("Profiil","Profiilipilt","Vaheta fotot","JPG, PNG või WebP. Vähendatakse automaatselt, kehtib kõikjal.","Isikuandmed","Kuvatav nimi","E-posti aadressi ei saa muuta.","Roll","Administraator","Liige","Salvesta","Salvestatud.","Salvestamine ebaõnnestus.","Välimus","Vali hele, tume või järgi süsteemi seadet.","Hele","Tume","Süsteem","Keel","Kehtib kõigile tekstidele ja vaadetele."),
 "lv": ("Profils","Profila attēls","Mainīt foto","JPG, PNG vai WebP. Tiek automātiski samazināts un izmantots visur.","Personas dati","Attēlojamais vārds","E-pasta adresi nevar mainīt.","Loma","Administrators","Dalībnieks","Saglabāt","Saglabāts.","Neizdevās saglabāt.","Izskats","Izvēlies gaišu, tumšu vai seko sistēmas iestatījumam.","Gaišs","Tumšs","Sistēma","Valoda","Attiecas uz visiem tekstiem un saskarnēm."),
 "pl": ("Profil","Zdjęcie profilowe","Zmień zdjęcie","JPG, PNG lub WebP. Automatycznie zmniejszane, używane wszędzie.","Dane osobowe","Wyświetlana nazwa","Adresu e-mail nie można zmienić.","Rola","Administrator","Członek","Zapisz","Zapisano.","Zapis nie powiódł się.","Wygląd","Wybierz jasny, ciemny lub podążaj za ustawieniem systemu.","Jasny","Ciemny","System","Język","Dotyczy wszystkich tekstów i interfejsów."),
 "cs": ("Profil","Profilová fotka","Změnit fotku","JPG, PNG nebo WebP. Automaticky se zmenší a platí všude.","Osobní údaje","Zobrazované jméno","E-mailovou adresu nelze změnit.","Role","Administrátor","Člen","Uložit","Uloženo.","Uložení se nezdařilo.","Vzhled","Zvol světlý, tmavý nebo se řiď nastavením systému.","Světlý","Tmavý","Systém","Jazyk","Platí pro všechny texty a obrazovky."),
 "hu": ("Profil","Profilkép","Fotó cseréje","JPG, PNG vagy WebP. Automatikusan kicsinyítve, mindenhol érvényes.","Személyes adatok","Megjelenített név","Az e-mail-cím nem módosítható.","Szerep","Adminisztrátor","Tag","Mentés","Mentve.","A mentés nem sikerült.","Megjelenés","Válassz világosat, sötétet, vagy kövesd a rendszerbeállítást.","Világos","Sötét","Rendszer","Nyelv","Minden szövegre és felületre érvényes."),
 "ro": ("Profil","Fotografie de profil","Schimbă fotografia","JPG, PNG sau WebP. Redimensionată automat, valabilă peste tot.","Date personale","Nume afișat","Adresa de e-mail nu poate fi schimbată.","Rol","Administrator","Membru","Salvează","Salvat.","Salvarea a eșuat.","Aspect","Alege luminos, întunecat sau urmează setarea sistemului.","Luminos","Întunecat","Sistem","Limbă","Se aplică tuturor textelor și interfețelor."),
 "el": ("Προφίλ","Φωτογραφία προφίλ","Αλλαγή φωτογραφίας","JPG, PNG ή WebP. Μικραίνει αυτόματα και ισχύει παντού.","Προσωπικά στοιχεία","Εμφανιζόμενο όνομα","Η διεύθυνση e-mail δεν αλλάζει.","Ρόλος","Διαχειριστής","Μέλος","Αποθήκευση","Αποθηκεύτηκε.","Η αποθήκευση απέτυχε.","Εμφάνιση","Επίλεξε φωτεινό, σκοτεινό ή ακολούθησε τη ρύθμιση συστήματος.","Φωτεινό","Σκοτεινό","Σύστημα","Γλώσσα","Ισχύει για όλα τα κείμενα και τις οθόνες."),
 "ru": ("Профиль","Фото профиля","Сменить фото","JPG, PNG или WebP. Автоматически уменьшается и действует везде.","Личные данные","Отображаемое имя","Адрес электронной почты изменить нельзя.","Роль","Администратор","Участник","Сохранить","Сохранено.","Не удалось сохранить.","Оформление","Выберите светлую, тёмную тему или следуйте системной настройке.","Светлая","Тёмная","Система","Язык","Действует для всех текстов и экранов."),
 "uk": ("Профіль","Фото профілю","Змінити фото","JPG, PNG або WebP. Автоматично зменшується і діє всюди.","Особисті дані","Відображуване ім'я","Адресу електронної пошти змінити не можна.","Роль","Адміністратор","Учасник","Зберегти","Збережено.","Не вдалося зберегти.","Оформлення","Виберіть світлу, темну тему або слідуйте системному налаштуванню.","Світла","Темна","Система","Мова","Діє для всіх текстів і екранів."),
 "ga": ("Próifíl","Grianghraf próifíle","Athraigh an grianghraf","JPG, PNG nó WebP. Laghdaítear go huathoibríoch é agus úsáidtear é i ngach áit.","Sonraí pearsanta","Ainm taispeána","Ní féidir an seoladh ríomhphoist a athrú.","Ról","Riarthóir","Ball","Sábháil","Sábháilte.","Theip ar an sábháil.","Cuma","Roghnaigh geal, dorcha nó lean socrú an chórais.","Geal","Dorcha","Córas","Teanga","Baineann sé le gach téacs agus comhéadan."),
}

root = Path(__file__).resolve().parent.parent / "src" / "i18n" / "dictionaries"
for loc, v in T.items():
    (profile, photo, change, photoHint, personal, dispName, emailLocked, role,
     roleAdmin, roleMember, save, saved, saveFailed, appearance, appearanceHint,
     light, dark, system, language, languageHint) = v
    f = root / f"{loc}.json"
    d = json.loads(f.read_text(encoding="utf-8"))
    d.setdefault("nav", {})["profile"] = d.get("nav", {}).get("profile") or profile
    d["profilePage"] = {
        "title": profile, "photo": photo, "changePhoto": change, "photoHint": photoHint,
        "personal": personal, "displayName": dispName, "emailLocked": emailLocked,
        "role": role, "roleAdmin": roleAdmin, "roleMember": roleMember,
        "save": save, "saved": saved, "saveFailed": saveFailed,
        "appearance": appearance, "appearanceHint": appearanceHint,
        "light": light, "dark": dark, "system": system,
    }
    d["settingsPage"] = {"language": language, "languageHint": languageHint}
    f.write_text(json.dumps(d, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(loc, "OK")
print("Fertig.")
